name: Manual Gradle Build
on:
  workflow_dispatch:
    inputs:
      gradleTask:
        description: 'Gradle task to run (e.g., build, test)'
        required: false
        default: 'build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: Product-Management

      - name: Build
        run: ./gradlew build --no-daemon
        working-directory: Product-Management
      - name: Upload JAR (Windows)
        uses: actions/upload-artifact@v4
        with:
            name: build-jar
            path: Product-Management\build\libs\*.jar
        env:
          CI: true

